version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12.13.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run linter
          command: npm run lint

  deploy:
    docker:
      - image: circleci/node:12.13.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build dist
          command: npm run build
      # - run:
      #     name: Zip dist
      #     command: zip -r dist dist/*
      # - run:
      #     name: Transfer dist.zip
      #     command: scp -o StrictHostKeyChecking=no ./dist.zip $DEVELOP_USER@$DEVELOP_IP:/home/$DEVELOP_USER/dist.zip
      # - run:
      #     name: Unzip dist.zip
      #     command: ssh -oStrictHostKeyChecking=no -v $DEVELOP_USER@$DEVELOP_IP "cd /home/$DEVELOP_USER; unzip ./dist.zip; rm -rf ./front-end/;mv ./dist/ ./front-end/; rm ./dist.zip;"

workflows:
  version: 2.1
  testing:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
  deployment:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master